---
name: auto-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Call webhook
            run: curl -k --fail-with-body -X POST ${{secrets.DEPLOY_WEBHOOK}}
